### ISSUE TITLE
Containers section is outdated

### ISSUE THREAD

**Issue by zwn** [PX4/dev.px4.io#8]
The section https://dev.px4.io/v1.9.0/en/test_and_ci/docker.html#px4_containers contains outdated information. For example there is no image `px4-dev-simulation` etc.

**Comment by TSC21** [comment]
Yes. That needs some updates. I will try to follow up till the end of the week.

**Comment by zwn** [comment]
The UI shows me you have responded a minute before I created the issue :laughing:. That is the fastest response ever. Anyway, the part about nvidia is outdated as well: https://dev.px4.io/v1.9.0/en/test_and_ci/docker.html#graphics-driver-issues. I believe the correct way to run nvidia based containers is to use `--runtime=nvidia` option for docker (after installing the correct packages). For more info see https://devblogs.nvidia.com/gpu-containers-runtime/.

**Comment by zwn** [comment]
Ok, so even more correct/current way is to use `--gpus all`. I have tested the following setup

```bash
PWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SRC_DIR=$PWD/Firmware

CCACHE_DIR=${HOME}/.ccache
mkdir -p "${CCACHE_DIR}"

docker run -it --rm -w "$SRC_DIR" \
	--gpus all \
	-e DISPLAY \
	-e XAUTHORITY \
	-e NVIDIA_VISIBLE_DEVICES=all \
	-e NVIDIA_DRIVER_CAPABILITIES=graphics,compat32,utility \
	-e CCACHE_DIR="${CCACHE_DIR}" \
	-v "/tmp/.X11-unix:/tmp/.X11-unix" \
	-v "$XAUTHORITY:$XAUTHORITY" \
	-v ${CCACHE_DIR}:${CCACHE_DIR}:rw \
	-v ${SRC_DIR}:${SRC_DIR}:rw \
	--publish 14556:14556/udp \
	px4io/px4-dev-simulation-bionic bash
```
when put inside a script one directory above the `Firmware` checkout. This is working for me on ubuntu 18.04 with nvidia gpu and 435 drivers installed. I am able to run both jmavsim and gazebo with hw opengl acceleration.

Feel free to use this in any way for the devguide.

**Comment by zwn** [comment]
Just a note: jmavsim works after dealing with https://github.com/PX4/containers/issues/206

**Comment by dagar** [comment]
This repository only hosts the generated gitbook, please use https://github.com/PX4/Devguide.
